// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchDownloadImages(arg1, arg2, arg3) {
  return window['go']['app']['App']['BatchDownloadImages'](arg1, arg2, arg3);
}

export function CancelImageDownload() {
  return window['go']['app']['App']['CancelImageDownload']();
}

export function CancelScrape() {
  return window['go']['app']['App']['CancelScrape']();
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function ClearCache() {
  return window['go']['app']['App']['ClearCache']();
}

export function ClearExpiredCache() {
  return window['go']['app']['App']['ClearExpiredCache']();
}

export function ClearLoginCache() {
  return window['go']['app']['App']['ClearLoginCache']();
}

export function DeleteDataFile(arg1) {
  return window['go']['app']['App']['DeleteDataFile'](arg1);
}

export function ExportArticles(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExportArticles'](arg1, arg2, arg3);
}

export function ExportCredentials() {
  return window['go']['app']['App']['ExportCredentials']();
}

export function ExtractArticleImages(arg1) {
  return window['go']['app']['App']['ExtractArticleImages'](arg1);
}

export function GetAppData() {
  return window['go']['app']['App']['GetAppData']();
}

export function GetAppVersion() {
  return window['go']['app']['App']['GetAppVersion']();
}

export function GetCacheStats() {
  return window['go']['app']['App']['GetCacheStats']();
}

export function GetDataDirectory() {
  return window['go']['app']['App']['GetDataDirectory']();
}

export function GetDefaultConfig() {
  return window['go']['app']['App']['GetDefaultConfig']();
}

export function GetLoginStatus() {
  return window['go']['app']['App']['GetLoginStatus']();
}

export function ImportCredentials() {
  return window['go']['app']['App']['ImportCredentials']();
}

export function ListDataFiles() {
  return window['go']['app']['App']['ListDataFiles']();
}

export function LoadConfig() {
  return window['go']['app']['App']['LoadConfig']();
}

export function LoadDataFile(arg1) {
  return window['go']['app']['App']['LoadDataFile'](arg1);
}

export function Login() {
  return window['go']['app']['App']['Login']();
}

export function Logout() {
  return window['go']['app']['App']['Logout']();
}

export function OpenDataFileDialog() {
  return window['go']['app']['App']['OpenDataFileDialog']();
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SearchAccount(arg1) {
  return window['go']['app']['App']['SearchAccount'](arg1);
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SelectSaveFile(arg1, arg2) {
  return window['go']['app']['App']['SelectSaveFile'](arg1, arg2);
}

export function StartScrape(arg1) {
  return window['go']['app']['App']['StartScrape'](arg1);
}

export function UpdateAppData(arg1) {
  return window['go']['app']['App']['UpdateAppData'](arg1);
}
