// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spider} from '../models';
import {app} from '../models';
import {models} from '../models';
import {storage} from '../models';
import {frontend} from '../models';
import {context} from '../models';

export function BatchDownloadImages(arg1:Array<spider.ImageInfo>,arg2:string,arg3:number):Promise<void>;

export function CancelImageDownload():Promise<void>;

export function CancelScrape():Promise<void>;

export function CheckForUpdates():Promise<app.VersionInfo>;

export function ClearCache():Promise<void>;

export function ClearExpiredCache():Promise<void>;

export function ClearLoginCache():Promise<void>;

export function ClearUpdateCache():Promise<void>;

export function DeleteDataFile(arg1:string):Promise<void>;

export function ExportArticles(arg1:Array<models.Article>,arg2:string,arg3:string):Promise<void>;

export function ExportCredentials():Promise<string>;

export function ExportToJSON(arg1:string):Promise<string>;

export function ExtractArticleImages(arg1:string):Promise<Array<spider.ImageInfo>>;

export function ForceQuit():Promise<void>;

export function GetAppData():Promise<models.AppData>;

export function GetAppVersion():Promise<string>;

export function GetCacheStats():Promise<Record<string, number>>;

export function GetCloseToTray():Promise<boolean>;

export function GetDataDirectory():Promise<string>;

export function GetDefaultConfig():Promise<models.Config>;

export function GetLoginStatus():Promise<models.LoginStatus>;

export function GetRememberChoice():Promise<boolean>;

export function GetUpdateIgnoredDate():Promise<string>;

export function HideToTray():Promise<void>;

export function ImportCredentials():Promise<void>;

export function ImportJSONFile(arg1:string):Promise<void>;

export function IsAutostartEnabled():Promise<boolean>;

export function IsAutostartSilent():Promise<boolean>;

export function ListDataFiles():Promise<Array<storage.DataFileInfo>>;

export function LoadConfig():Promise<models.Config>;

export function LoadDataFile(arg1:string):Promise<Array<models.Article>>;

export function Login():Promise<void>;

export function Logout():Promise<void>;

export function OpenDataFileDialog():Promise<string>;

export function SaveConfig(arg1:models.Config):Promise<void>;

export function SearchAccount(arg1:string):Promise<Array<models.Account>>;

export function SelectDirectory():Promise<string>;

export function SelectSaveFile(arg1:string,arg2:Array<frontend.FileFilter>):Promise<string>;

export function SetAutostart(arg1:boolean,arg2:boolean):Promise<void>;

export function SetCloseToTray(arg1:boolean):Promise<void>;

export function SetRememberChoice(arg1:boolean):Promise<void>;

export function SetUpdateIgnoredDate(arg1:string):Promise<void>;

export function ShouldBlockClose():Promise<boolean>;

export function ShowWindow():Promise<void>;

export function StartScrape(arg1:models.ScrapeConfig):Promise<Array<models.Article>>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateAppData(arg1:Array<models.Article>):Promise<void>;
